name: Create a Python file

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new Python file
        run: |
          echo 'print("Hello, World!")' > new_script.py
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add new_script.py
          git commit -m "Add new_script.py"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
